sudo: false
language: python
cache: pip
matrix:
  include:
    - env: TOXENV=py35-django111
      python: 3.5
    - env: TOXENV=py36-django111
      python: 3.6
    - env: TOXENV=py37-django111
      python: 3.7
    - env: TOXENV=py35-django111
      python: 3.8
    - env: TOXENV=py35-django22
      python: 3.5
    - env: TOXENV=py36-django22
      python: 3.6
    - env: TOXENV=py37-django22
      python: 3.7
    - env: TOXENV=py35-django22
      python: 3.8
    - env: TOXENV=py35-django30
      python: 3.5
    - env: TOXENV=py36-django30
      python: 3.6
    - env: TOXENV=py37-django30
      python: 3.7
    - env: TOXENV=py35-django30
      python: 3.8
install:
  - pip install tox
script:
  - tox
after_success:
  - pip install codecov
  - coverage report
  - codecov