sudo: false
language: python
python: 3.5
env:
  matrix:
    - TOXENV=py27-django18
    - TOXENV=py34-django18
    - TOXENV=py35-django18
    - TOXENV=py27-django19
    - TOXENV=py34-django19
    - TOXENV=py35-django19
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install tox codecov
branches:
  only:
    - master
script:
  - tox
after_success:
  - coverage report
  - codecov